services:
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: container-dev
    env_file: 
      - .env
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dev-net
    restart: always
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:latest
    container_name: container-mysql-dev
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql
    networks:
      - dev-net
    restart: always

  redis:
    image: redis:latest
    container_name: container-redis-dev
    ports:
      - '6380:6379'
    volumes:
      - redis-db:/data
    networks:
      - dev-net
    restart: always

networks:
  dev-net:

volumes:
  dev_mysql_data:
  redis-db:
