name: Deploy FE (Next.js) & BE to EC2 with PM2

on:
  push:
    branches:
      - feat/add-staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Next.js FE
        working-directory: ./ecomgrove-fe
        run: |
          npm ci
          npm run build

      - name: Upload FE build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            ecomgrove-fe/.next
            ecomgrove-fe/public
            ecomgrove-fe/package.json
            ecomgrove-fe/package-lock.json
            ecomgrove-fe/next.config.js
            ecomgrove-fe/ecosystem.config.js
          target: /var/www/EcomGrove/ecomgrove-fe

      - name: SSH & Restart FE with PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/EcomGrove/ecomgrove-fe
            npm ci --omit=dev
            pm2 restart ecomgrove-fe || pm2 start ecosystem.config.js --only frontend

      - name: Deploy BE on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/EcomGrove
            git fetch origin
            git checkout feat/add-staging
            git reset --hard origin/feat/add-staging
            npm ci
            pm2 restart ecomgrove-be || pm2 start ecosystem.config.js --only backend
