name: Deploy FE & BE to EC2 with PM2

on:
  push:
    branches:
      - feat/add-staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying EcomGrove..."

            cd /var/www/EcomGrove || exit 1

            echo "Pulling latest changes..."
            git fetch origin
            git checkout feat/add-staging
            git reset --hard origin/feat/add-staging

            echo "Deploying backend..."
            cd ecomgrove-be
            npm ci
            pm2 start ecosystem.config.js --only backend || pm2 restart ecomgrove-be

            echo "Deploying frontend..."
            cd ../ecomgrove-fe
            npm ci
            npm run build
            pm2 start ecosystem.config.js --only frontend || pm2 restart ecomgrove-fe
