name: Deploy FE (Next.js) & BE to EC2 with PM2

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - check structure
        run: |
          pwd
          ls -la
          ls -la ecomgrove_fe

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build FE
        working-directory: ./ecomgrove_fe
        run: |
          npm ci
          npm run build

      - name: Debug - Check build files
        run: |
          ls -la ecomgrove_fe
          ls -la ecomgrove_fe/.next || echo "No .next found"

      - name: Upload FE build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            .next
            public
            package.json
            package-lock.json
            next.config.js
            ecosystem.config.js
          target: /var/www/EcomGrove/ecomgrove_fe
          port: 22
          strip_components: 0
          overwrite: true
        working-directory: ./ecomgrove_fe

      - name: SSH & Restart FE with PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/EcomGrove/ecomgrove_fe
            npm ci --omit=dev
            pm2 restart ecomgrove-fe || pm2 start ecosystem.config.js --only frontend

      - name: SSH & Deploy BE on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/EcomGrove
            git fetch origin
            git checkout feat/add-staging
            git reset --hard origin/feat/add-staging
            cd ecomgrove_be
            npm ci
            pm2 restart ecomgrove-be || pm2 start ecosystem.config.js --only backend
